(function(){
'use strict';
var W='http://schemas.openxmlformats.org/wordprocessingml/2006/main',A='http://schemas.openxmlformats.org/drawingml/2006/main',R='http://schemas.openxmlformats.org/officeDocument/2006/relationships',DB='KerjaDesaMasterTemplateDB',STORE='files',KEY='report',M=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember'];
function openDB(){return new Promise(function(ok,no){var q=indexedDB.open(DB,1);q.onupgradeneeded=function(){if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=function(){ok(q.result)};q.onerror=function(){no(q.error)}})}
function getM(){return openDB().then(function(db){return new Promise(function(ok,no){var q=db.transaction(STORE,'readonly').objectStore(STORE).get(KEY);q.onsuccess=function(){db.close();ok(q.result||null)};q.onerror=function(){db.close();no(q.error)}})})}
function putM(b,n){return openDB().then(function(db){return new Promise(function(ok,no){var t=db.transaction(STORE,'readwrite');t.objectStore(STORE).put({blob:b,name:n,savedAt:Date.now()},KEY);t.oncomplete=function(){db.close();ok()};t.onerror=function(){db.close();no(t.error)}})})}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function clean(s){return String(s==null?'':s).replace(/\u00ad/g,'').replace(/\s+/g,' ').trim()}
function X(s){return new DOMParser().parseFromString(s,'application/xml')} function XS(d){return new XMLSerializer().serializeToString(d)}
function P(b){return Array.prototype.filter.call(b.children,function(x){return x.localName==='p'})} function T(b){return Array.prototype.filter.call(b.children,function(x){return x.localName==='tbl'})} function Rw(t){return Array.prototype.filter.call(t.children,function(x){return x.localName==='tr'})} function C(r){return Array.prototype.filter.call(r.children,function(x){return x.localName==='tc'})} function text(e){return Array.prototype.map.call(e.getElementsByTagNameNS(W,'t'),function(x){return x.textContent||''}).join('')}
function setP(p,v){var fr=Array.prototype.find.call(p.children,function(x){return x.localName==='r'}),rp=fr&&fr.getElementsByTagNameNS(W,'rPr')[0]?fr.getElementsByTagNameNS(W,'rPr')[0].cloneNode(true):null;Array.prototype.slice.call(p.childNodes).forEach(function(n){if(n.nodeType===1&&n.localName!=='pPr')p.removeChild(n)});String(v||'').split('\n').forEach(function(line,i){if(i){var rr=p.ownerDocument.createElementNS(W,'w:r'),br=p.ownerDocument.createElementNS(W,'w:br');rr.appendChild(br);p.appendChild(rr)}var r=p.ownerDocument.createElementNS(W,'w:r');if(rp)r.appendChild(rp.cloneNode(true));var t=p.ownerDocument.createElementNS(W,'w:t');t.setAttributeNS('http://www.w3.org/XML/1998/namespace','xml:space','preserve');t.textContent=line;r.appendChild(t);p.appendChild(r)})}
function setC(c,v){Array.prototype.slice.call(c.children).forEach(function(n){if(n.localName!=='tcPr')c.removeChild(n)});var p=c.ownerDocument.createElementNS(W,'w:p');c.appendChild(p);setP(p,v)} function clearD(c){Array.prototype.slice.call(c.getElementsByTagNameNS(W,'drawing')).forEach(function(n){if(n.parentNode)n.parentNode.removeChild(n)})}
function dl(d){var m=String(d||'').match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);return m?String(m[1]).padStart(2,'0')+' '+M[Number(m[2])-1]+' '+m[3]:String(d||'')} function dk(d){return typeof window.dateKey==='function'?window.dateKey(d):String(d||'')} function vc(s){var p=String(s||'').split('/');return String(p[p.length-1]||s||'-').toLowerCase().replace(/\b[a-z]/g,function(c){return c.toUpperCase()})}
function short(d){var l=clean(d).toLowerCase(),r=[[/gedung koperasi|koperasi desa merah putih/,'Monitoring Progres Pembangunan Gedung Koperasi Desa Merah Putih'],[/rabat beton.*jalan.*paminggalan|jalan poros paminggalan.*limbua/,'Monitoring Progres Pekerjaan Rabat Beton Jalan Poros Paminggalan menuju Desa Limbua'],[/jembatan dekker/,'Monitoring Progres Pembangunan Jembatan Dekker Dusun Palla-Pallang'],[/drainase/,'Monitoring Progres Pembangunan Drainase'],[/titik nol|rehabilitasi jalan setapak/,'Monitoring Titik Nol Rehabilitasi Jalan Setapak'],[/pra[- ]?musrenbang/,'Koordinasi Persiapan Pra-Musrenbang Dusun'],[/musrenbangdes|musyawarah.*rkpdes/,'Musrenbang Desa dalam rangka Penyusunan RKPDes dan DU-RKPDes Tahun 2027'],[/perubahan apbdes/,'Koordinasi Persiapan Perubahan APBDes Tahun Anggaran 2026'],[/rancangan apbdes/,'Koordinasi Penyusunan Rancangan APBDes'],[/monev.*dana desa|monitoring dan evaluasi dana desa/,'Rapat Koordinasi TPP P3MD terkait Percepatan Monev Dana Desa'],[/sembako|pkh|blt/,'Verifikasi dan Sinkronisasi Data Penerima Bantuan'],[/indeks desa|verval|pemutakhiran data/,'Verifikasi, Perbaikan dan Pemutakhiran Data Indeks Desa'],[/baliho.*apbdes|infografis.*apbdes/,'Koordinasi Percepatan Pemasangan Baliho/Infografis APBDes']];for(var i=0;i<r.length;i++)if(r[i][0].test(l))return r[i][1];return clean(d)}
function ready(){getM().then(function(x){var s=document.getElementById('masterReportStatus');if(s)s.innerHTML=x?'✅ Master tersimpan: <b>'+esc(x.name)+'</b>.':'Template master belum disimpan.'}).catch(function(){})}
window.kdLoadMasterReportTemplate=function(inp){var f=inp&&inp.files&&inp.files[0];if(!f)return;if(!/\.docx$/i.test(f.name)){alert('Gunakan file master laporan .docx');return}f.arrayBuffer().then(function(b){return putM(new Blob([b],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),f.name)}).then(ready).catch(function(e){alert('Gagal menyimpan master: '+e.message)})};window.kdInitMasterReportStatus=ready;
window.downloadWord=async function(){try{var saved=await getM();if(!saved)throw new Error('Upload master DOCX laporan asli satu kali pada bagian Master Template.');var drp=data.docs&&data.docs.drp&&data.docs.drp.parsed;if(!drp||!drp.all||!drp.all.length)throw new Error('DRP belum diproses.');var zip=await JSZip.loadAsync(saved.blob);var doc=X(await zip.file('word/document.xml').async('string')),rel=X(await zip.file('word/_rels/document.xml.rels').async('string')),body=doc.getElementsByTagNameNS(W,'body')[0],p=P(body),t=T(body);if(t.length<12)throw new Error('Master DOCX tidak sesuai struktur asli (12 tabel).');var h=drp.header||{},per=h.periode||periodLabel(),month=monthNameFromPeriod(per),year=yearFromPeriod(per),acts=drp.all.slice().sort(function(a,b){return String(a.tanggal).localeCompare(String(b.tanggal))||Number(a.no||0)-Number(b.no||0)}),visit=[],seen={};acts.forEach(function(a){var k=dk(a.tanggal);if(k&&!seen[k]){seen[k]=1;visit.push(a)}});
function rep(rx,v){for(var i=0;i<p.length;i++)if(rx.test(clean(text(p[i])))){setP(p[i],v);return}} function find(rx){for(var i=0;i<p.length;i++)if(rx.test(clean(text(p[i]))))return p[i];return null}
rep(/^LAPORAN KUNJUNGAN LAPANGAN SEPTEMBER$/i,'LAPORAN KUNJUNGAN LAPANGAN '+month.toUpperCase());rep(/^KECAMATAN SENDANA$/i,'KECAMATAN SENDANA');rep(/^KABUPATEN MAJENE$/i,'KABUPATEN MAJENE');rep(/^PROVINSI SULAWSEI BARAT$/i,'PROVINSI SULAWESI BARAT');rep(/^TAHUN 2026$/i,'TAHUN '+year);rep(/^BULAN SEPTEMBER TAHUN 2026$/i,'BULAN '+month.toUpperCase()+' TAHUN '+year);rep(/^C\. Tujuan Kunjugan Lapangan$/i,'C. Tujuan Kunjungan Lapangan');rep(/^D\. Hasil Kunjugan Lapangan$/i,'D. Hasil Kunjungan Lapangan');rep(/^G\. Dokumentasi Kunjugan Lapangan$/i,'G. Dokumentasi Kunjungan Lapangan');
var ids=[[/^NIK\s*:/i,'NIK: 760503312910050'],[/^Nama Lengkap\s*:/i,'Nama Lengkap: SUDARMIN ARIPUDDIN'],[/^Kecamatan\s*:/i,'Kecamatan: Sendana'],[/^Kabupaten\s*:/i,'Kabupaten: Majene'],[/^Provinsi\s*:/i,'Provinsi: Sulawesi Barat'],[/^Posisi\s*:/i,'Posisi: PLD'],[/^Jabatan\s*:/i,'Jabatan: Pendamping Lokal Desa']];ids.forEach(function(x){rep(x[0],x[1])});
var br=Rw(t[0]);for(var i=0;i<20;i++){var rr=br[3+i],cc=rr?C(rr):[],a=visit[i];if(cc.length<4)continue;if(a){setC(cc[0],'Hari ke-'+(i+1));setC(cc[1],dl(a.tanggal));setC(cc[2],'SENDANA');setC(cc[3],vc(a.lokasi))}else cc.forEach(function(c){setC(c,'')})}if(br[br.length-1])setC(C(br[br.length-1])[0],'Total Hari Kunjungan Lapangan Bulan '+month+' Tahun '+year+' : '+visit.length+' Hari');
var n=typeof deriveNarratives==='function'?deriveNarratives(acts):{tujuan:[],hasil:[],follow:[],recs:[]};var ci=p.findIndex(function(x){return /^C\. Tujuan Kunjungan Lapangan$/i.test(clean(text(x)))}),di=p.findIndex(function(x){return /^D\. Hasil Kunjungan Lapangan$/i.test(clean(text(x)))});if(ci>=0){var cp=p.slice(ci+1,di>ci?di:p.length).filter(function(x){return clean(text(x))});if(cp[0])setP(cp[0],'Kunjungan lapangan bertujuan untuk melaksanakan pendampingan secara langsung kepada Pemerintah Desa dan masyarakat dalam memastikan proses pembangunan, perencanaan, pelaksanaan kegiatan, serta pengelolaan program desa berjalan sesuai dengan rencana dan ketentuan yang berlaku. Kunjungan dilakukan dengan melihat kondisi faktual di lapangan, melakukan koordinasi dengan pihak terkait, mencermati perkembangan kegiatan, serta memberikan pendampingan terhadap hal-hal yang memerlukan tindak lanjut.');for(i=0;i<14;i++)if(cp[i+1])setP(cp[i+1],n.tujuan&&n.tujuan[i]||'')}
var dr=Rw(t[1]);for(i=0;i<22;i++){rr=dr[i+1];if(!rr)continue;cc=C(rr);if(cc.length<4)continue;if(acts[i]){setC(cc[0],String(i+1));setC(cc[1],dl(acts[i].tanggal));setC(cc[2],vc(acts[i].lokasi));setC(cc[3],clean(acts[i].deskripsi))}else cc.forEach(function(c){setC(c,'')})}
var ds=p.findIndex(function(x){return /^Hasil kunjungan lapangan menunjukkan beberapa capaian/i.test(clean(text(x)))});if(ds>=0&&n.hasil){var z=0;for(i=ds+1;i<p.length&&z<7;i++){if(/^E\./i.test(clean(text(p[i]))))break;if(clean(text(p[i]))){setP(p[i],n.hasil[z]||'');z++}}}
var ei=p.findIndex(function(x){return /^E\. Langkah Tindak Lanjut Penanganan Lapangan$/i.test(clean(text(x)))}),fi=p.findIndex(function(x){return /^F\. Rekomendasi$/i.test(clean(text(x)))}),gi=p.findIndex(function(x){return /^G\. Dokumentasi Kunjungan Lapangan$/i.test(clean(text(x)))});if(ei>=0){z=0;for(i=ei+1;i<(fi>ei?fi:p.length)&&z<11;i++)if(clean(text(p[i]))){setP(p[i],z===0?'Berdasarkan hasil kunjungan lapangan selama Bulan '+month+' '+year+', tindak lanjut yang dilakukan difokuskan pada penyelesaian temuan, penyempurnaan data, pemantauan kegiatan pembangunan, penguatan administrasi, serta koordinasi dengan unsur terkait.':(n.follow&&n.follow[z-1]||''));z++}}if(fi>=0){z=0;for(i=fi+1;i<(gi>fi?gi:p.length)&&z<10;i++)if(clean(text(p[i]))){setP(p[i],z===0?'Berdasarkan hasil kunjungan lapangan yang telah dilaksanakan selama Bulan '+month+' '+year+' di wilayah Kecamatan Sendana, Kabupaten Majene, terdapat beberapa rekomendasi yang perlu menjadi perhatian Pemerintah Desa sebagai bahan perbaikan dan tindak lanjut pada periode berikutnya.':(n.recs&&n.recs[z-1]||''));z++}}var dp=find(/^Sendana\s+/i);if(dp)setP(dp,'Sendana 30 '+month+' '+year);
var rels=Array.prototype.slice.call(rel.getElementsByTagNameNS(R,'Relationship')),rm={};rels.forEach(function(x){rm[x.getAttribute('Id')]=x.getAttribute('Target')});var photos=(window.activityPhotos||[]).filter(function(x){return x&&x.url&&x.date}).slice().sort(function(a,b){return dk(a.date).localeCompare(dk(b.date))}),slots=[];photos.forEach(function(ph){var ac=acts.find(function(x){return dk(x.tanggal)===dk(ph.date)});if(ac)slots.push({p:ph,a:ac})});var gt=t.slice(2,12);for(i=0;i<gt.length;i++){var gr=Rw(gt[i]);if(gr.length<2)continue;var top=C(gr[0]),bot=C(gr[1]);for(var j=0;j<2;j++){var it=slots[i*2+j];if(!it){setC(top[j],'');clearD(bot[j]);continue}setC(top[j],'Lokasi: '+vc(it.a.lokasi)+'\nTanggal '+it.p.date+'\nKegiatan ; '+short(it.a.deskripsi));var bl=Array.prototype.slice.call(bot[j].getElementsByTagNameNS(A,'blip'));if(bl.length){var rid=bl[0].getAttributeNS(R,'embed'),target=rm[rid],mm=String(it.p.url).match(/^data:image\/[^;]+;base64,(.+)$/);if(target&&mm)zip.file('word/'+target.replace(/^\.\.\//,''),mm[1],{base64:true})}}}
zip.file('word/document.xml',XS(doc));var blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',compression:'DEFLATE'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Laporan_Kunjungan_Lapangan_'+month+'_2026.docx';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href)},3000);
 }catch(e){console.error(e);alert('Gagal membuat laporan dari master: '+(e&&e.message||e))}};
setTimeout(ready,600);
})();