FROM node:22-alpine

RUN apk add --no-cache poppler-utils
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev --no-audit --no-fund
COPY . .
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm","start"]
